### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by mmagnuski**
This small PR:
- changes imports in `__init__.py` so that `pacpy` works well on python 3
- makes travis test `pacpy` on python 3 as well

### CODE REVIEW

**Comment by mmagnuski** [comment]
I'll try to change the travis script to test for python 3.

**Comment by mmagnuski** [comment]
Sorry for the `Merge branch 'master' of https://github.com/voytekresearch/pacpy` commit, I am not sure how to get rid of these.

**Comment by mmagnuski** [comment]
BTW - this fixes #9

**Comment by mmagnuski** [comment]
Oh, I just noticed the conflicts - I'll try to resolve today/tomorrow.

**Comment by srcole** [comment]
this good to go? @mmagnuski @parenthetical-e

**Comment by mmagnuski** [comment]
From my side - yes.

**Comment by mmagnuski** [comment]
(but I could try removing the merge commits if you prefer)

**Pull request merged**
